#!/usr/bin/env bash
# A Bash script to transfer file from a client to a server.
# Using the scp linux command, we're taking  the following arguments
# PATH_TO_FILE to be copied to server, USER on server IP of server
# LOCATION to copy to on server and PATH_TO_IDENTITY_FILE for user auth
if [ "$#" -lt 3 ]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
